using Melanchall.DryWetMidi.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Makku.MIDI.APCMiniMk2.Constants
{
    public static class Colour
    {
        public static readonly SevenBitNumber Black = new(0);
        public static readonly SevenBitNumber DarkGray = new(1);
        public static readonly SevenBitNumber Gray = new(2);
        public static readonly SevenBitNumber White = new(3);
        public static readonly SevenBitNumber Red = new(4);
        public static readonly SevenBitNumber BrightRed = new(5);
        public static readonly SevenBitNumber DarkRed = new(6);
        public static readonly SevenBitNumber VeryDarkRed = new(7);
        public static readonly SevenBitNumber Orange = new(8);
        public static readonly SevenBitNumber BrightOrange = new(9);
        public static readonly SevenBitNumber DarkOrange = new(10);
        public static readonly SevenBitNumber VeryDarkOrange = new(11);
        public static readonly SevenBitNumber Yellow = new(12);
        public static readonly SevenBitNumber BrightYellow = new(13);
        public static readonly SevenBitNumber DarkYellow = new(14);
        public static readonly SevenBitNumber VeryDarkYellow = new(15);
        public static readonly SevenBitNumber LightGreen = new(16);
        public static readonly SevenBitNumber BrightGreen = new(17);
        public static readonly SevenBitNumber DarkGreen = new(18);
        public static readonly SevenBitNumber VeryDarkGreen = new(19);
        public static readonly SevenBitNumber Green = new(20);
        public static readonly SevenBitNumber BrightLimeGreen = new(21);
        public static readonly SevenBitNumber DarkLimeGreen = new(22);
        public static readonly SevenBitNumber VeryDarkLimeGreen = new(23);
        public static readonly SevenBitNumber LightLimeGreen = new(24);
        public static readonly SevenBitNumber BrightLightLimeGreen = new(25);
        public static readonly SevenBitNumber DarkLightLimeGreen = new(26);
        public static readonly SevenBitNumber VeryDarkLightLimeGreen = new(27);
        public static readonly SevenBitNumber LightAquaGreen = new(28);
        public static readonly SevenBitNumber BrightAquaGreen = new(29);
        public static readonly SevenBitNumber DarkAquaGreen = new(30);
        public static readonly SevenBitNumber VeryDarkAquaGreen = new(31);
        public static readonly SevenBitNumber LightMintGreen = new(32);
        public static readonly SevenBitNumber BrightMintGreen = new(33);
        public static readonly SevenBitNumber DarkMintGreen = new(34);
        public static readonly SevenBitNumber VeryDarkMintGreen = new(35);
        public static readonly SevenBitNumber LightSkyBlue = new(36);
        public static readonly SevenBitNumber BrightSkyBlue = new(37);
        public static readonly SevenBitNumber DarkSkyBlue = new(38);
        public static readonly SevenBitNumber VeryDarkSkyBlue = new(39);
        public static readonly SevenBitNumber LightBlue = new(40);
        public static readonly SevenBitNumber BrightBlue = new(41);
        public static readonly SevenBitNumber DarkBlue = new(42);
        public static readonly SevenBitNumber VeryDarkBlue = new(43);
        public static readonly SevenBitNumber LightPurple = new(44);
        public static readonly SevenBitNumber BrightPurple = new(45);
        public static readonly SevenBitNumber DarkPurple = new(46);
        public static readonly SevenBitNumber VeryDarkPurple = new(47);
        public static readonly SevenBitNumber LightViolet = new(48);
        public static readonly SevenBitNumber BrightViolet = new(49);
        public static readonly SevenBitNumber DarkViolet = new(50);
        public static readonly SevenBitNumber VeryDarkViolet = new(51);
        public static readonly SevenBitNumber LightMagenta = new(52);
        public static readonly SevenBitNumber BrightMagenta = new(53);
        public static readonly SevenBitNumber DarkMagenta = new(54);
        public static readonly SevenBitNumber VeryDarkMagenta = new(55);
        public static readonly SevenBitNumber LightPink = new(56);
        public static readonly SevenBitNumber BrightPink = new(57);
        public static readonly SevenBitNumber DarkPink = new(58);
        public static readonly SevenBitNumber VeryDarkPink = new(59);
        public static readonly SevenBitNumber LightCoral = new(60);
        public static readonly SevenBitNumber BrightCoral = new(61);
        public static readonly SevenBitNumber DarkCoral = new(62);
        public static readonly SevenBitNumber VeryDarkCoral = new(63);
        public static readonly SevenBitNumber LightBrown = new(64);
        public static readonly SevenBitNumber BrightBrown = new(65);
        public static readonly SevenBitNumber DarkBrown = new(66);
        public static readonly SevenBitNumber VeryDarkBrown = new(67);
        public static readonly SevenBitNumber LightOlive = new(68);
        public static readonly SevenBitNumber BrightOlive = new(69);
        public static readonly SevenBitNumber DarkOlive = new(70);
        public static readonly SevenBitNumber VeryDarkOlive = new(71);
        public static readonly SevenBitNumber LightRed = new(72);
        public static readonly SevenBitNumber BrightRed2 = new(73);
        public static readonly SevenBitNumber DarkRed2 = new(74);
        public static readonly SevenBitNumber VeryDarkRed2 = new(75);
        public static readonly SevenBitNumber LightGreen2 = new(76);
        public static readonly SevenBitNumber BrightGreen2 = new(77);
        public static readonly SevenBitNumber DarkGreen2 = new(78);
        public static readonly SevenBitNumber VeryDarkGreen2 = new(79);
        public static readonly SevenBitNumber LightBlue2 = new(80);
        public static readonly SevenBitNumber BrightBlue2 = new(81);
        public static readonly SevenBitNumber DarkBlue2 = new(82);
        public static readonly SevenBitNumber VeryDarkBlue2 = new(83);
        public static readonly SevenBitNumber LightPurple2 = new(84);
        public static readonly SevenBitNumber BrightPurple2 = new(85);
        public static readonly SevenBitNumber DarkPurple2 = new(86);
        public static readonly SevenBitNumber VeryDarkPurple2 = new(87);
        public static readonly SevenBitNumber LightMagenta2 = new(88);
        public static readonly SevenBitNumber BrightMagenta2 = new(89);
        public static readonly SevenBitNumber DarkMagenta2 = new(90);
        public static readonly SevenBitNumber VeryDarkMagenta2 = new(91);
        public static readonly SevenBitNumber LightPink2 = new(92);
        public static readonly SevenBitNumber BrightPink2 = new(93);
        public static readonly SevenBitNumber DarkPink2 = new(94);
        public static readonly SevenBitNumber VeryDarkPink2 = new(95);
        public static readonly SevenBitNumber LightCoral2 = new(96);
        public static readonly SevenBitNumber BrightCoral2 = new(97);
        public static readonly SevenBitNumber DarkCoral2 = new(98);
        public static readonly SevenBitNumber VeryDarkCoral2 = new(99);
        public static readonly SevenBitNumber LightBrown2 = new(100);
        public static readonly SevenBitNumber BrightBrown2 = new(101);
        public static readonly SevenBitNumber DarkBrown2 = new(102);
        public static readonly SevenBitNumber VeryDarkBrown2 = new(103);
        public static readonly SevenBitNumber LightOlive2 = new(104);
        public static readonly SevenBitNumber BrightOlive2 = new(105);
        public static readonly SevenBitNumber DarkOlive2 = new(106);
        public static readonly SevenBitNumber VeryDarkOlive2 = new(107);
        public static readonly SevenBitNumber LightRed2 = new(108);
        public static readonly SevenBitNumber BrightRed3 = new(109);
        public static readonly SevenBitNumber DarkRed3 = new(110);
        public static readonly SevenBitNumber VeryDarkRed3 = new(111);
        public static readonly SevenBitNumber LightGreen3 = new(112);
        public static readonly SevenBitNumber BrightGreen3 = new(113);
        public static readonly SevenBitNumber DarkGreen3 = new(114);
        public static readonly SevenBitNumber VeryDarkGreen3 = new(115);
        public static readonly SevenBitNumber LightBlue3 = new(116);
        public static readonly SevenBitNumber BrightBlue3 = new(117);
        public static readonly SevenBitNumber DarkBlue3 = new(118);
        public static readonly SevenBitNumber VeryDarkBlue3 = new(119);
        public static readonly SevenBitNumber LightPurple3 = new(120);
        public static readonly SevenBitNumber BrightPurple3 = new(121);
        public static readonly SevenBitNumber DarkPurple3 = new(122);
        public static readonly SevenBitNumber VeryDarkPurple3 = new(123);
        public static readonly SevenBitNumber LightMagenta3 = new(124);
    }
}
